vertical_whitespace:
  max_empty_lines: 2

line_length:
    warning: 96

disabled_rules:
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - switch_case_alignment
  - force_cast
  - comment_spacing